### ISSUE TITLE
Integrate the realsense camera into the physical robot

### ISSUE THREAD

**Issue by GPrathap** [LCAS/hunter_robot#8]
### Description

1. Add necessary dependencies https://github.com/LCAS/aoc_strawberry_scenario/blob/humble_dev/.devcontainer/docker/ros2/script/install_extra_libs_hardware_specific.sh#L83
2. Add necessary packages https://github.com/LCAS/aoc_strawberry_scenario/blob/humble_dev/.devcontainer/docker/ros2/repos/hunter_platform.repos

**Comment by marc-hanheide** [comment]
I feel this has progressed... close?

**Comment by ibrahimhroob** [comment]
@Cyano0 I think we have decided to stick with ZED camera.
